### ISSUE TITLE
gmaps configuration

### ISSUE THREAD

**Issue by kristianmandrup** [apneadiving/Google-Maps-for-Rails#265]
Would be nice if you could enable loading the config from a YAML file automatically.

Example:

config/gmap4rails.yaml

``` yaml
provider:
  name: dfddsgsgsd 
  key: ssss
```

and so on... also it should warn if no key provided. Looks like google maps v3 also requires a key now?
